spring.application.name=ninjas

# criar comunicação com o banco de dados

# url de conexão com o banco (endereço + porta + nome do banco)
spring.datasource.url = jdbc:postgresql://localhost:5432/ninjas

# usuário d banco de dados
spring.datasource.username = postgres

# senha do banco de dados
spring.datasource.password = postdba

# driver responsável pela conexão com postg
spring,datasource.driver-class-name = org.postgresql.Driver

# define como o hibernate vai gerenciar as tabelas (update= cria/atualiza sem apagar dados)
spring.jpa.hibernate.ddl-auto = update

# mostra no console as consultas sql executadas
spring.jpa.show-sql = true

# formata o sql exibido no console para facilitar leitura
spring.jpa.properties.hibernate.format_sql = true

# define o tipo de banco utilizado (dialeto do postg)
spring.jpa.database-plataform = org.hibernate.dialect.PostgreSQLDialect